version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /var/usr/app/node_modules
      - .:/var/usr/app

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /var/usr/app/node_modules
      - .:/var/usr/app
    command: ["npm", "run", "test"]
